### ISSUE TITLE
Unable to set password

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-esphome-api#2]
A password from the config is being used when setting up the connection https://github.com/bitfocus/companion-module-esphome-api/blob/c9e86079773b61f39afe1e8b2e347443ba01614f/src/index.ts#L49
But this is not exposed in the ui, so I am unable to set the password https://github.com/bitfocus/companion-module-esphome-api/blob/main/src/config.ts

**Comment by bradleywehmeier** [comment]
Yep. Thanks for pointing that out. I've updated the config UI and tested it out.
Solved in `v1.1.0`. Waiting to see what is needed for companion 3.0 to get this merged into companion.

**Comment by Julusian** [comment]
Thanks, thats better now.

I feel like this could sneak into 2.4.1 if that release happens as I would class this as a bug fix. 
But details on what is needed for 3.0 is coming soon
